### ISSUE TITLE
Question: about BL31 address and size setting

### ISSUE THREAD

**Issue by KunYi** [OpenNuvoton/MA35D1_arm-trusted-firmware-v2.3#1]
I see the below code comment say   **0x2803C000 is reserved to IBR**

https://github.com/OpenNuvoton/MA35D1_arm-trusted-firmware-v2.3/blob/2777723e8c29f295dd2fdf57c8a3c4c03226ce5e/plat/nuvoton/ma35d1/ma35d1_def.h#L58-L61

but  code defined (MA35D1_BL31_BASE  + MA35D1_BL31_SIZE) = **0x2803F000** is overlapped.
let me confused now.

**Comment by ychuang3** [comment]
The comment "/* 0x2803C000 is reserved to IBR */"  is obsoleted configuration. We will remove it.
The BL31 size limitation 0x1A000 is correct.

**Comment by KunYi** [comment]
Sounds great.
